/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../app/app.module';
import * as i2 from '../../app/app.component';
import * as i3 from '../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as i4 from '../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as i5 from '../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as i6 from '../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as i7 from '../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as i8 from '../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as i9 from '../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as i10 from './app.component.ngfactory';
import * as i11 from '@angular/common';
import * as i12 from '@angular/platform-browser';
import * as i13 from '@angular/animations/browser';
import * as i14 from '@angular/platform-browser/animations';
import * as i15 from '@angular/animations';
import * as i16 from '@angular/http';
import * as i17 from '@angular/forms';
import * as i18 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as i19 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as i20 from '@ng-bootstrap/ng-bootstrap/alert/alert-config';
import * as i21 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar-config';
import * as i22 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip-config';
import * as i23 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead-config';
import * as i24 from '@ng-bootstrap/ng-bootstrap/accordion/accordion-config';
import * as i25 from '@ng-bootstrap/ng-bootstrap/carousel/carousel-config';
import * as i26 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-calendar';
import * as i27 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-i18n';
import * as i28 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-date-parser-formatter';
import * as i29 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-config';
import * as i30 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as i31 from '@ng-bootstrap/ng-bootstrap/pagination/pagination-config';
import * as i32 from '@ng-bootstrap/ng-bootstrap/popover/popover-config';
import * as i33 from '@ng-bootstrap/ng-bootstrap/rating/rating-config';
import * as i34 from '@ng-bootstrap/ng-bootstrap/tabset/tabset-config';
import * as i35 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker-config';
import * as i36 from 'primeng/components/common/messageservice';
import * as i37 from '../../app/message/message.service';
import * as i38 from '../../app/signalR/signalR.service';
import * as i39 from 'primeng/components/common/shared';
import * as i40 from 'primeng/components/button/button';
import * as i41 from 'primeng/components/progressbar/progressbar';
import * as i42 from 'primeng/components/messages/messages';
import * as i43 from 'primeng/components/fileupload/fileupload';
import * as i44 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as i45 from '@ng-bootstrap/ng-bootstrap/buttons/buttons.module';
import * as i46 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as i47 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as i48 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as i49 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as i50 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as i51 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as i52 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as i53 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as i54 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as i55 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as i56 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as i57 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as i58 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as i59 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as i60 from '@ng-bootstrap/ng-bootstrap/index';
import * as i61 from 'primeng/components/paginator/paginator';
import * as i62 from 'primeng/components/datatable/datatable';
import * as i63 from 'primeng/components/growl/growl';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.NgbAlertNgFactory,i4.NgbTooltipWindowNgFactory,i5.NgbTypeaheadWindowNgFactory,
              i6.NgbDatepickerNgFactory,i7.NgbModalBackdropNgFactory,i8.NgbModalWindowNgFactory,
              i9.NgbPopoverWindowNgFactory,i10.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i11.NgLocalization,i11.NgLocaleLocalization,[i0.LOCALE_ID]),
          i0.ɵmpd(4608,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(5120,i0.APP_ID,
              i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i12.DomSanitizer,
              i12.ɵe,[i11.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i12.DomSanitizer]),
          i0.ɵmpd(4608,i12.HAMMER_GESTURE_CONFIG,i12.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i12.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i12.ɵDomEventsPlugin(p0_0),new i12.ɵKeyEventsPlugin(p1_0),
                new i12.ɵHammerGesturesPlugin(p2_0,p2_1)];
          },[i11.DOCUMENT,i11.DOCUMENT,i11.DOCUMENT,i12.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i12.EventManager,i12.EventManager,[i12.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i12.ɵDomSharedStylesHost,i12.ɵDomSharedStylesHost,[i11.DOCUMENT]),
          i0.ɵmpd(4608,i12.ɵDomRendererFactory2,i12.ɵDomRendererFactory2,[i12.EventManager,
              i12.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i13.AnimationDriver,i14.ɵc,([] as any[])),
          i0.ɵmpd(5120,i13.ɵAnimationStyleNormalizer,i14.ɵd,([] as any[])),i0.ɵmpd(4608,
              i13.ɵAnimationEngine,i14.ɵb,[i13.AnimationDriver,i13.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i14.ɵe,[i12.ɵDomRendererFactory2,i13.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(6144,i12.ɵSharedStylesHost,(null as any),[i12.ɵDomSharedStylesHost]),
          i0.ɵmpd(4608,i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i12.Meta,
              i12.Meta,[i11.DOCUMENT]),i0.ɵmpd(4608,i12.Title,i12.Title,[i11.DOCUMENT]),
          i0.ɵmpd(4608,i15.AnimationBuilder,i14.ɵBrowserAnimationBuilder,[i0.RendererFactory2,
              i12.DOCUMENT]),i0.ɵmpd(4608,i16.BrowserXhr,i16.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i16.ResponseOptions,i16.BaseResponseOptions,([] as any[])),
          i0.ɵmpd(5120,i16.XSRFStrategy,i16.ɵb,([] as any[])),i0.ɵmpd(4608,i16.XHRBackend,
              i16.XHRBackend,[i16.BrowserXhr,i16.ResponseOptions,i16.XSRFStrategy]),
          i0.ɵmpd(4608,i16.RequestOptions,i16.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i16.Http,i16.ɵc,[i16.XHRBackend,i16.RequestOptions]),i0.ɵmpd(4608,i17.ɵi,
              i17.ɵi,([] as any[])),i0.ɵmpd(4608,i18.NgbModalStack,i18.NgbModalStack,
              [i0.ApplicationRef,i0.Injector,i0.ComponentFactoryResolver]),i0.ɵmpd(4608,
              i19.NgbModal,i19.NgbModal,[i0.ComponentFactoryResolver,i0.Injector,i18.NgbModalStack]),
          i0.ɵmpd(4608,i20.NgbAlertConfig,i20.NgbAlertConfig,([] as any[])),i0.ɵmpd(4608,
              i21.NgbProgressbarConfig,i21.NgbProgressbarConfig,([] as any[])),i0.ɵmpd(4608,
              i22.NgbTooltipConfig,i22.NgbTooltipConfig,([] as any[])),i0.ɵmpd(4608,
              i23.NgbTypeaheadConfig,i23.NgbTypeaheadConfig,([] as any[])),i0.ɵmpd(4608,
              i24.NgbAccordionConfig,i24.NgbAccordionConfig,([] as any[])),i0.ɵmpd(4608,
              i25.NgbCarouselConfig,i25.NgbCarouselConfig,([] as any[])),i0.ɵmpd(4608,
              i26.NgbCalendar,i26.NgbCalendarGregorian,([] as any[])),i0.ɵmpd(4608,
              i27.NgbDatepickerI18n,i27.NgbDatepickerI18nDefault,([] as any[])),i0.ɵmpd(4608,
              i28.NgbDateParserFormatter,i28.NgbDateISOParserFormatter,([] as any[])),
          i0.ɵmpd(4608,i29.NgbDatepickerConfig,i29.NgbDatepickerConfig,([] as any[])),
          i0.ɵmpd(4608,i30.NgbDropdownConfig,i30.NgbDropdownConfig,([] as any[])),
          i0.ɵmpd(4608,i31.NgbPaginationConfig,i31.NgbPaginationConfig,([] as any[])),
          i0.ɵmpd(4608,i32.NgbPopoverConfig,i32.NgbPopoverConfig,([] as any[])),i0.ɵmpd(4608,
              i33.NgbRatingConfig,i33.NgbRatingConfig,([] as any[])),i0.ɵmpd(4608,
              i34.NgbTabsetConfig,i34.NgbTabsetConfig,([] as any[])),i0.ɵmpd(4608,
              i35.NgbTimepickerConfig,i35.NgbTimepickerConfig,([] as any[])),i0.ɵmpd(4608,
              i16.ɵg,i16.ɵg,([] as any[])),i0.ɵmpd(4608,i16.JSONPBackend,i16.ɵa,[i16.ɵg,
              i16.ResponseOptions]),i0.ɵmpd(5120,i16.Jsonp,i16.ɵd,[i16.JSONPBackend,
              i16.RequestOptions]),i0.ɵmpd(4608,i36.MessageService,i36.MessageService,
              ([] as any[])),i0.ɵmpd(4608,i37.CustomMessageService,i37.CustomMessageService,
              [i36.MessageService]),i0.ɵmpd(4608,i38.SignalRService,i38.SignalRService,
              ([] as any[])),i0.ɵmpd(512,i11.CommonModule,i11.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i12.ɵa,([] as any[])),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any) => {
                return [i12.ɵc(p0_0,p0_1)];
              },[[2,i12.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i12.BrowserModule,i12.BrowserModule,[[3,i12.BrowserModule]]),
          i0.ɵmpd(512,i14.BrowserAnimationsModule,i14.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i39.SharedModule,i39.SharedModule,([] as any[])),i0.ɵmpd(512,
              i40.ButtonModule,i40.ButtonModule,([] as any[])),i0.ɵmpd(512,i41.ProgressBarModule,
              i41.ProgressBarModule,([] as any[])),i0.ɵmpd(512,i42.MessagesModule,
              i42.MessagesModule,([] as any[])),i0.ɵmpd(512,i43.FileUploadModule,i43.FileUploadModule,
              ([] as any[])),i0.ɵmpd(512,i16.HttpModule,i16.HttpModule,([] as any[])),
          i0.ɵmpd(512,i17.ɵba,i17.ɵba,([] as any[])),i0.ɵmpd(512,i17.FormsModule,i17.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i44.NgbAlertModule,i44.NgbAlertModule,([] as any[])),
          i0.ɵmpd(512,i45.NgbButtonsModule,i45.NgbButtonsModule,([] as any[])),i0.ɵmpd(512,
              i46.NgbCollapseModule,i46.NgbCollapseModule,([] as any[])),i0.ɵmpd(512,
              i47.NgbProgressbarModule,i47.NgbProgressbarModule,([] as any[])),i0.ɵmpd(512,
              i48.NgbTooltipModule,i48.NgbTooltipModule,([] as any[])),i0.ɵmpd(512,
              i49.NgbTypeaheadModule,i49.NgbTypeaheadModule,([] as any[])),i0.ɵmpd(512,
              i50.NgbAccordionModule,i50.NgbAccordionModule,([] as any[])),i0.ɵmpd(512,
              i51.NgbCarouselModule,i51.NgbCarouselModule,([] as any[])),i0.ɵmpd(512,
              i52.NgbDatepickerModule,i52.NgbDatepickerModule,([] as any[])),i0.ɵmpd(512,
              i53.NgbDropdownModule,i53.NgbDropdownModule,([] as any[])),i0.ɵmpd(512,
              i54.NgbModalModule,i54.NgbModalModule,([] as any[])),i0.ɵmpd(512,i55.NgbPaginationModule,
              i55.NgbPaginationModule,([] as any[])),i0.ɵmpd(512,i56.NgbPopoverModule,
              i56.NgbPopoverModule,([] as any[])),i0.ɵmpd(512,i57.NgbRatingModule,
              i57.NgbRatingModule,([] as any[])),i0.ɵmpd(512,i58.NgbTabsetModule,i58.NgbTabsetModule,
              ([] as any[])),i0.ɵmpd(512,i59.NgbTimepickerModule,i59.NgbTimepickerModule,
              ([] as any[])),i0.ɵmpd(512,i60.NgbRootModule,i60.NgbRootModule,([] as any[])),
          i0.ɵmpd(512,i61.PaginatorModule,i61.PaginatorModule,([] as any[])),i0.ɵmpd(512,
              i62.DataTableModule,i62.DataTableModule,([] as any[])),i0.ɵmpd(512,i63.GrowlModule,
              i63.GrowlModule,([] as any[])),i0.ɵmpd(512,i16.JsonpModule,i16.JsonpModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiUDovRmlsZVVwbG9hZGVyL0ZpbGVVcGxvYWRlci5XZWJHdWkvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vUDovRmlsZVVwbG9hZGVyL0ZpbGVVcGxvYWRlci5XZWJHdWkvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
