/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './file-upload/file-upload.component.ngfactory';
import * as i2 from '../../app/file-upload/file-upload.service';
import * as i3 from '@angular/http';
import * as i4 from '../../app/file-upload/file-upload.component';
import * as i5 from '../../app/message/message.service';
import * as i6 from './file-download/file-download.component.ngfactory';
import * as i7 from '../../app/file-download/file-download.service';
import * as i8 from '../../app/file-download/file-download.component';
import * as i9 from '../node_modules/@ng-bootstrap/ng-bootstrap/tabset/tabset.ngfactory';
import * as i10 from '@ng-bootstrap/ng-bootstrap/tabset/tabset';
import * as i11 from '@ng-bootstrap/ng-bootstrap/tabset/tabset-config';
import * as i12 from '../node_modules/primeng/components/growl/growl.ngfactory';
import * as i13 from 'primeng/components/dom/domhandler';
import * as i14 from 'primeng/components/growl/growl';
import * as i15 from 'primeng/components/common/messageservice';
import * as i16 from './test/test.ngfactory';
import * as i17 from '../../app/test/test';
import * as i18 from '../../app/signalR/signalR.service';
import * as i19 from '../../app/app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
function View_AppComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n            '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),2,'file-uploader',([] as any[]),(null as any),(null as any),
      (null as any),i1.View_FileUploadComponent_0,i1.RenderType_FileUploadComponent)),
      i0.ɵprd(512,(null as any),i2.UploadService,i2.UploadService,[i3.Http]),i0.ɵdid(49152,
          (null as any),0,i4.FileUploadComponent,[i2.UploadService,i5.CustomMessageService],
          {multiple:[0,'multiple']},(null as any)),(_l()(),i0.ɵted((null as any),['\n        ']))],
      (_ck,_v) => {
        const currVal_0:any = true;
        _ck(_v,3,0,currVal_0);
      },(null as any));
}
function View_AppComponent_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n            '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),2,'file-download',([] as any[]),(null as any),(null as any),
      (null as any),i6.View_FileDownloadComponent_0,i6.RenderType_FileDownloadComponent)),
      i0.ɵprd(512,(null as any),i7.DownloadService,i7.DownloadService,[i3.Http]),i0.ɵdid(114688,
          (null as any),0,i8.FileDownloadComponent,[i7.DownloadService],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n        ']))],(_ck,_v) => {
    _ck(_v,3,0);
  },(null as any));
}
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),21,'ngb-tabset',
      ([] as any[]),(null as any),(null as any),(null as any),i9.View_NgbTabset_0,
      i9.RenderType_NgbTabset)),i0.ɵdid(2146304,(null as any),1,i10.NgbTabset,[i11.NgbTabsetConfig],
      {justify:[0,'justify']},(null as any)),i0.ɵqud(603979776,1,{tabs:1}),(_l()(),
      i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      7,'ngb-tab',[['title','Upload documents']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),i0.ɵdid(16384,[[1,4]],2,i10.NgbTab,([] as any[]),
      {title:[0,'title']},(null as any)),i0.ɵqud(335544320,2,{contentTpl:0}),i0.ɵqud(335544320,
      3,{titleTpl:0}),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵand(0,
      (null as any),(null as any),1,(null as any),View_AppComponent_1)),i0.ɵdid(16384,
      [[2,4]],0,i10.NgbTabContent,[i0.TemplateRef],(null as any),(null as any)),(_l()(),
      i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),['\n    '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),7,'ngb-tab',[['title','Download documents']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(16384,[[1,4]],2,i10.NgbTab,([] as any[]),{title:[0,'title']},(null as any)),
      i0.ɵqud(335544320,4,{contentTpl:0}),i0.ɵqud(335544320,5,{titleTpl:0}),(_l()(),
          i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵand(0,(null as any),(null as any),
          1,(null as any),View_AppComponent_2)),i0.ɵdid(16384,[[4,4]],0,i10.NgbTabContent,
          [i0.TemplateRef],(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),
          ['\n\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'p-growl',([] as any[]),
          (null as any),(null as any),(null as any),i12.View_Growl_0,i12.RenderType_Growl)),
      i0.ɵprd(512,(null as any),i13.DomHandler,i13.DomHandler,([] as any[])),i0.ɵdid(4636672,
          (null as any),0,i14.Growl,[i0.ElementRef,i13.DomHandler,i0.IterableDiffers,
              [2,i15.MessageService]],(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'clock-component',
          ([] as any[]),(null as any),(null as any),(null as any),i16.View_ClockComponent_0,
          i16.RenderType_ClockComponent)),i0.ɵdid(49152,(null as any),0,i17.ClockComponent,
          [i18.SignalRService,i0.NgZone],(null as any),(null as any))],(_ck,_v) => {
    var _co:i19.AppComponent = _v.component;
    const currVal_0:any = _co.currentJustify;
    _ck(_v,1,0,currVal_0);
    const currVal_1:any = 'Upload documents';
    _ck(_v,5,0,currVal_1);
    const currVal_2:any = 'Download documents';
    _ck(_v,14,0,currVal_2);
    _ck(_v,25,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(49152,(null as any),0,i19.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i19.AppComponent> = i0.ɵccf('my-app',
    i19.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiUDovRmlsZVVwbG9hZGVyL0ZpbGVVcGxvYWRlci5XZWJHdWkvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vUDovRmlsZVVwbG9hZGVyL0ZpbGVVcGxvYWRlci5XZWJHdWkvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9QOi9GaWxlVXBsb2FkZXIvRmlsZVVwbG9hZGVyLldlYkd1aS9hcHAvYXBwLmh0bWwiLCJuZzovLy9QOi9GaWxlVXBsb2FkZXIvRmlsZVVwbG9hZGVyLldlYkd1aS9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8bmdiLXRhYnNldCBbanVzdGlmeV09XCJjdXJyZW50SnVzdGlmeVwiPlxyXG4gICAgPG5nYi10YWIgdGl0bGU9XCJVcGxvYWQgZG9jdW1lbnRzXCI+XHJcbiAgICAgICAgPG5nLXRlbXBsYXRlIG5nYlRhYkNvbnRlbnQ+XHJcbiAgICAgICAgICAgIDxmaWxlLXVwbG9hZGVyIFttdWx0aXBsZV09XCJ0cnVlXCI+PC9maWxlLXVwbG9hZGVyPlxyXG4gICAgICAgIDwvbmctdGVtcGxhdGU+XHJcbiAgICA8L25nYi10YWI+XHJcbiAgICA8bmdiLXRhYiB0aXRsZT1cIkRvd25sb2FkIGRvY3VtZW50c1wiPlxyXG4gICAgICAgIDxuZy10ZW1wbGF0ZSBuZ2JUYWJDb250ZW50PlxyXG4gICAgICAgICAgICA8ZmlsZS1kb3dubG9hZD48L2ZpbGUtZG93bmxvYWQ+XHJcbiAgICAgICAgPC9uZy10ZW1wbGF0ZT5cclxuICAgIDwvbmdiLXRhYj5cclxuPC9uZ2ItdGFic2V0PlxyXG5cclxuPHAtZ3Jvd2w+PC9wLWdyb3dsPlxyXG48Y2xvY2stY29tcG9uZW50PjwvY2xvY2stY29tcG9uZW50PiIsIjxteS1hcHA+PC9teS1hcHA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDRW1DLG1EQUN2QjtNQUFBO01BQUE7YUFBQSx1RUFBQTtVQUFBO1VBQUEseUNBQWlEOztRQUFsQztRQUFmLFdBQWUsU0FBZjs7OztvQkFJdUIsbURBQ3ZCO01BQUE7TUFBQTthQUFBLDJFQUFBO1VBQUE7VUFBQSxlQUErQjtJQUEvQjs7OztvQkFSWjtNQUFBOzZCQUFBLFVBQUE7TUFBQSxxRUFBdUM7YUFBQSw0QkFDbkM7TUFBQTtNQUFBLHFDQUFBO01BQUE7TUFBQSxnQkFBa0MsK0NBQzlCO01BQUEseUVBQUE7TUFBQSwwRUFFYzthQUFBLDRCQUNSO01BQ1Y7VUFBQTthQUFBO2FBQUEsK0RBQW9DO2lCQUFBLGdDQUNoQztVQUFBLDZDQUFBO1VBQUEsOENBRWM7VUFBQSxhQUNSLHVDQUNEO1VBQUEsV0FFYjtVQUFBO2FBQUEsdUVBQUE7VUFBQTtjQUFBLHFEQUFtQjtVQUFBLFNBQ25CO1VBQUE7dUNBQUEsVUFBQTtVQUFBOztJQWRZO0lBQVosV0FBWSxTQUFaO0lBQ2E7SUFBVCxXQUFTLFNBQVQ7SUFLUztJQUFULFlBQVMsU0FBVDtJQU9KOzs7O29CQ2JBO01BQUE7YUFBQTs7OzsifQ==
