/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/test/test';
import * as i2 from '../../../app/signalR/signalR.service';
const styles_ClockComponent:any[] = ([] as any[]);
export const RenderType_ClockComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ClockComponent,data:{}});
export function View_ClockComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),4,'div',[['id','timediv']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n        '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          [' ',''])),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),
          [' \n  ']))],(null as any),(_ck,_v) => {
    var _co:i1.ClockComponent = _v.component;
    const currVal_0:any = _co.allMessages;
    _ck(_v,4,0,currVal_0);
  });
}
export function View_ClockComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'clock-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_ClockComponent_0,
      RenderType_ClockComponent)),i0.ɵdid(49152,(null as any),0,i1.ClockComponent,
      [i2.SignalRService,i0.NgZone],(null as any),(null as any))],(null as any),(null as any));
}
export const ClockComponentNgFactory:i0.ComponentFactory<i1.ClockComponent> = i0.ɵccf('clock-component',
    i1.ClockComponent,View_ClockComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiUDovRmlsZVVwbG9hZGVyL0ZpbGVVcGxvYWRlci5XZWJHdWkvYXBwL3Rlc3QvdGVzdC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9QOi9GaWxlVXBsb2FkZXIvRmlsZVVwbG9hZGVyLldlYkd1aS9hcHAvdGVzdC90ZXN0LnRzIiwibmc6Ly8vUDovRmlsZVVwbG9hZGVyL0ZpbGVVcGxvYWRlci5XZWJHdWkvYXBwL3Rlc3QvdGVzdC50cy5DbG9ja0NvbXBvbmVudC5odG1sIiwibmc6Ly8vUDovRmlsZVVwbG9hZGVyL0ZpbGVVcGxvYWRlci5XZWJHdWkvYXBwL3Rlc3QvdGVzdC50cy5DbG9ja0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXYgaWQ9XCJ0aW1lZGl2XCI+XG4gICAgICAgIDxwPiB7e2FsbE1lc3NhZ2VzIH19PC9wPlxuICAgIDwvZGl2PiBcbiAgIiwiPGNsb2NrLWNvbXBvbmVudD48L2Nsb2NrLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsMkNBQ0k7TUFBQTtNQUFBLDhCQUFrQjtNQUNkO1VBQUEsMERBQUc7VUFBQSxXQUFxQiwyQ0FDdEI7VUFBQTs7SUFEQztJQUFBOzs7O29CQ0ZYO01BQUE7K0JBQUEsVUFBQTtNQUFBOzs7In0=
